language: scala
scala:
  - 2.11.12
  - 2.12.10
  - 2.13.0
jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
script:
  - sbt clean coverage test
after_success:
  - sbt coveralls
